[project]
name = "dragon-ball"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "frank", email = "frankcampos85@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "boto3>=1.43.55",
    "duckdb>=1.5.5",
    "httpx>=0.28.1",
    "kagglehub[pandas-datasets]>=1.0.2",
    "python-dotenv>=1.2.2",
    "tenacity>=9.1.4",
]

[project.scripts]
dragon-ball = "dragon_ball:main"

[build-system]
requires = ["uv_build>=0.9.4,<0.10.0"]
build-backend = "uv_build"
