[project]
name = "dragon-ball"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "frank", email = "frankcampos85@gmail.com" }
]
requires-python = ">=3.11"
dependencies = []

[project.scripts]
dragon-ball = "dragon_ball:main"

[build-system]
requires = ["uv_build>=0.9.4,<0.10.0"]
build-backend = "uv_build"
